using System.Collections.Generic;
using System.Globalization;
using System.IO;
using NUnit.Framework;

namespace System;

/// <summary>
/// Cross-checks <see cref="MXFP4"/> dequantized output bit-for-bit against Microsoft's microxcaling
/// reference (the OCP Microscaling reference implementation). Vectors generated by
/// TestData/generate_mx_golden.py and embedded as a resource.
/// </summary>
[TestFixture]
public class MxFp4GoldenTests {

  private static IEnumerable<(float[] input, float[] expected)> ReadVectors() {
    var asm = typeof(MxFp4GoldenTests).Assembly;
    string? name = null;
    foreach (var n in asm.GetManifestResourceNames())
      if (n.EndsWith("mxfp4_ref.tsv", StringComparison.Ordinal)) {
        name = n;
        break;
      }

    Assert.That(name, Is.Not.Null, "embedded resource 'mxfp4_ref.tsv' not found");
    using var reader = new StreamReader(asm.GetManifestResourceStream(name!)!);
    string? line;
    while ((line = reader.ReadLine()) != null) {
      if (line.Length == 0 || line[0] == '#')
        continue;
      var parts = line.Split('|');
      yield return (ParseFloats(parts[0]), ParseFloats(parts[1]));
    }
  }

  private static float[] ParseFloats(string csv) {
    var tokens = csv.Split(',');
    var result = new float[tokens.Length];
    for (var i = 0; i < tokens.Length; ++i)
      result[i] = float.Parse(tokens[i], NumberStyles.Float, CultureInfo.InvariantCulture);
    return result;
  }

  [Test]
  public void MXFP4_Encode_MatchesMicroxcalingReference() {
    var caseIndex = 0;
    foreach (var (input, expected) in ReadVectors()) {
      var decoded = MXFP4.Encode(input).ToArray();
      Assert.That(decoded.Length, Is.EqualTo(expected.Length), $"case {caseIndex} length");
      for (var i = 0; i < expected.Length; ++i)
        Assert.That(decoded[i], Is.EqualTo(expected[i]), $"case {caseIndex} index {i} (input {input[i]})");
      ++caseIndex;
    }

    Assert.That(caseIndex, Is.GreaterThan(0), "no reference vectors loaded");
  }
}
