github: [Hawkynt]
nuget: [FrameworkExtensions.Backports, FrameworkExtensions.Corlib, FrameworkExtensions.DirectoryServices, FrameworkExtensions.System.Drawing, FrameworkExtensions.System.Windows.Forms, FrameworkExtensions.PresentationCore]
custom: ["https://www.paypal.me/hawkynt"]