#region (c)2010-2020 Hawkynt
/*
  This file is part of Hawkynt's .NET Framework extensions.

    Hawkynt's .NET Framework extensions are free software: 
    you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Hawkynt's .NET Framework extensions is distributed in the hope that 
    it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
    the GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Hawkynt's .NET Framework extensions.  
    If not, see <http://www.gnu.org/licenses/>.
*/
#endregion

/* ATTENTION: This file is generated by a tool. All changes will be reverted upon next run ! */


#if NETFX_4
using System.Diagnostics.Contracts;
#endif
#if NETFX_45
using System.Runtime.CompilerServices;
#endif
using word = System.UInt16;
using dword = System.UInt32;
using qword = System.UInt64;

// ReSharper disable RedundantCast
// ReSharper disable UnusedMember.Global
// ReSharper disable PartialTypeWithSinglePart

namespace System {
  internal static partial class TimeSpanExtensions {
    
      
    /// <summary>
    /// Multiplies the time by a given factor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="multiplier">The multiplier.</param>
    /// <returns>A multiple of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan MultipliedWith(this TimeSpan @this, sbyte multiplier) => TimeSpan.FromTicks((long)(@this.Ticks * multiplier));

    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan DividedBy(this TimeSpan @this, sbyte divisor) => TimeSpan.FromTicks((long)(@this.Ticks / (double)divisor));
    
    /// <summary>
    /// Creates a timespan from the given milliseconds.
    /// </summary>
    /// <param name="this">This Number of milliseconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Milliseconds(this sbyte @this) => TimeSpan.FromMilliseconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given seconds.
    /// </summary>
    /// <param name="this">This Number of seconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Seconds(this sbyte @this) => TimeSpan.FromSeconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given minutes.
    /// </summary>
    /// <param name="this">This Number of minutes.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Minutes(this sbyte @this) => TimeSpan.FromMinutes(@this);
    
    /// <summary>
    /// Creates a timespan from the given hours.
    /// </summary>
    /// <param name="this">This Number of hours.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Hours(this sbyte @this) => TimeSpan.FromHours(@this);
    
    /// <summary>
    /// Creates a timespan from the given days.
    /// </summary>
    /// <param name="this">This Number of days.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Days(this sbyte @this) => TimeSpan.FromDays(@this);
    
    /// <summary>
    /// Creates a timespan from the given weeks.
    /// </summary>
    /// <param name="this">This Number of weeks.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Weeks(this sbyte @this) => TimeSpan.FromDays(7*@this);
    
      
    /// <summary>
    /// Multiplies the time by a given factor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="multiplier">The multiplier.</param>
    /// <returns>A multiple of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan MultipliedWith(this TimeSpan @this, byte multiplier) => TimeSpan.FromTicks((long)(@this.Ticks * multiplier));

    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan DividedBy(this TimeSpan @this, byte divisor) => TimeSpan.FromTicks((long)(@this.Ticks / (double)divisor));
    
    /// <summary>
    /// Creates a timespan from the given milliseconds.
    /// </summary>
    /// <param name="this">This Number of milliseconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Milliseconds(this byte @this) => TimeSpan.FromMilliseconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given seconds.
    /// </summary>
    /// <param name="this">This Number of seconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Seconds(this byte @this) => TimeSpan.FromSeconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given minutes.
    /// </summary>
    /// <param name="this">This Number of minutes.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Minutes(this byte @this) => TimeSpan.FromMinutes(@this);
    
    /// <summary>
    /// Creates a timespan from the given hours.
    /// </summary>
    /// <param name="this">This Number of hours.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Hours(this byte @this) => TimeSpan.FromHours(@this);
    
    /// <summary>
    /// Creates a timespan from the given days.
    /// </summary>
    /// <param name="this">This Number of days.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Days(this byte @this) => TimeSpan.FromDays(@this);
    
    /// <summary>
    /// Creates a timespan from the given weeks.
    /// </summary>
    /// <param name="this">This Number of weeks.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Weeks(this byte @this) => TimeSpan.FromDays(7*@this);
    
      
    /// <summary>
    /// Multiplies the time by a given factor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="multiplier">The multiplier.</param>
    /// <returns>A multiple of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan MultipliedWith(this TimeSpan @this, short multiplier) => TimeSpan.FromTicks((long)(@this.Ticks * multiplier));

    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan DividedBy(this TimeSpan @this, short divisor) => TimeSpan.FromTicks((long)(@this.Ticks / (double)divisor));
    
    /// <summary>
    /// Creates a timespan from the given milliseconds.
    /// </summary>
    /// <param name="this">This Number of milliseconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Milliseconds(this short @this) => TimeSpan.FromMilliseconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given seconds.
    /// </summary>
    /// <param name="this">This Number of seconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Seconds(this short @this) => TimeSpan.FromSeconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given minutes.
    /// </summary>
    /// <param name="this">This Number of minutes.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Minutes(this short @this) => TimeSpan.FromMinutes(@this);
    
    /// <summary>
    /// Creates a timespan from the given hours.
    /// </summary>
    /// <param name="this">This Number of hours.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Hours(this short @this) => TimeSpan.FromHours(@this);
    
    /// <summary>
    /// Creates a timespan from the given days.
    /// </summary>
    /// <param name="this">This Number of days.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Days(this short @this) => TimeSpan.FromDays(@this);
    
    /// <summary>
    /// Creates a timespan from the given weeks.
    /// </summary>
    /// <param name="this">This Number of weeks.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Weeks(this short @this) => TimeSpan.FromDays(7*@this);
    
      
    /// <summary>
    /// Multiplies the time by a given factor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="multiplier">The multiplier.</param>
    /// <returns>A multiple of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan MultipliedWith(this TimeSpan @this, word multiplier) => TimeSpan.FromTicks((long)(@this.Ticks * multiplier));

    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan DividedBy(this TimeSpan @this, word divisor) => TimeSpan.FromTicks((long)(@this.Ticks / (double)divisor));
    
    /// <summary>
    /// Creates a timespan from the given milliseconds.
    /// </summary>
    /// <param name="this">This Number of milliseconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Milliseconds(this word @this) => TimeSpan.FromMilliseconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given seconds.
    /// </summary>
    /// <param name="this">This Number of seconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Seconds(this word @this) => TimeSpan.FromSeconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given minutes.
    /// </summary>
    /// <param name="this">This Number of minutes.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Minutes(this word @this) => TimeSpan.FromMinutes(@this);
    
    /// <summary>
    /// Creates a timespan from the given hours.
    /// </summary>
    /// <param name="this">This Number of hours.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Hours(this word @this) => TimeSpan.FromHours(@this);
    
    /// <summary>
    /// Creates a timespan from the given days.
    /// </summary>
    /// <param name="this">This Number of days.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Days(this word @this) => TimeSpan.FromDays(@this);
    
    /// <summary>
    /// Creates a timespan from the given weeks.
    /// </summary>
    /// <param name="this">This Number of weeks.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Weeks(this word @this) => TimeSpan.FromDays(7*@this);
    
      
    /// <summary>
    /// Multiplies the time by a given factor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="multiplier">The multiplier.</param>
    /// <returns>A multiple of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan MultipliedWith(this TimeSpan @this, int multiplier) => TimeSpan.FromTicks((long)(@this.Ticks * multiplier));

    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan DividedBy(this TimeSpan @this, int divisor) => TimeSpan.FromTicks((long)(@this.Ticks / (double)divisor));
    
    /// <summary>
    /// Creates a timespan from the given milliseconds.
    /// </summary>
    /// <param name="this">This Number of milliseconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Milliseconds(this int @this) => TimeSpan.FromMilliseconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given seconds.
    /// </summary>
    /// <param name="this">This Number of seconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Seconds(this int @this) => TimeSpan.FromSeconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given minutes.
    /// </summary>
    /// <param name="this">This Number of minutes.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Minutes(this int @this) => TimeSpan.FromMinutes(@this);
    
    /// <summary>
    /// Creates a timespan from the given hours.
    /// </summary>
    /// <param name="this">This Number of hours.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Hours(this int @this) => TimeSpan.FromHours(@this);
    
    /// <summary>
    /// Creates a timespan from the given days.
    /// </summary>
    /// <param name="this">This Number of days.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Days(this int @this) => TimeSpan.FromDays(@this);
    
    /// <summary>
    /// Creates a timespan from the given weeks.
    /// </summary>
    /// <param name="this">This Number of weeks.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Weeks(this int @this) => TimeSpan.FromDays(7*@this);
    
      
    /// <summary>
    /// Multiplies the time by a given factor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="multiplier">The multiplier.</param>
    /// <returns>A multiple of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan MultipliedWith(this TimeSpan @this, dword multiplier) => TimeSpan.FromTicks((long)(@this.Ticks * multiplier));

    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan DividedBy(this TimeSpan @this, dword divisor) => TimeSpan.FromTicks((long)(@this.Ticks / (double)divisor));
    
    /// <summary>
    /// Creates a timespan from the given milliseconds.
    /// </summary>
    /// <param name="this">This Number of milliseconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Milliseconds(this dword @this) => TimeSpan.FromMilliseconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given seconds.
    /// </summary>
    /// <param name="this">This Number of seconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Seconds(this dword @this) => TimeSpan.FromSeconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given minutes.
    /// </summary>
    /// <param name="this">This Number of minutes.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Minutes(this dword @this) => TimeSpan.FromMinutes(@this);
    
    /// <summary>
    /// Creates a timespan from the given hours.
    /// </summary>
    /// <param name="this">This Number of hours.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Hours(this dword @this) => TimeSpan.FromHours(@this);
    
    /// <summary>
    /// Creates a timespan from the given days.
    /// </summary>
    /// <param name="this">This Number of days.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Days(this dword @this) => TimeSpan.FromDays(@this);
    
    /// <summary>
    /// Creates a timespan from the given weeks.
    /// </summary>
    /// <param name="this">This Number of weeks.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Weeks(this dword @this) => TimeSpan.FromDays(7*@this);
    
      
    /// <summary>
    /// Multiplies the time by a given factor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="multiplier">The multiplier.</param>
    /// <returns>A multiple of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan MultipliedWith(this TimeSpan @this, long multiplier) => TimeSpan.FromTicks((long)(@this.Ticks * multiplier));

    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan DividedBy(this TimeSpan @this, long divisor) => TimeSpan.FromTicks((long)(@this.Ticks / (double)divisor));
    
    /// <summary>
    /// Creates a timespan from the given milliseconds.
    /// </summary>
    /// <param name="this">This Number of milliseconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Milliseconds(this long @this) => TimeSpan.FromMilliseconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given seconds.
    /// </summary>
    /// <param name="this">This Number of seconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Seconds(this long @this) => TimeSpan.FromSeconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given minutes.
    /// </summary>
    /// <param name="this">This Number of minutes.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Minutes(this long @this) => TimeSpan.FromMinutes(@this);
    
    /// <summary>
    /// Creates a timespan from the given hours.
    /// </summary>
    /// <param name="this">This Number of hours.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Hours(this long @this) => TimeSpan.FromHours(@this);
    
    /// <summary>
    /// Creates a timespan from the given days.
    /// </summary>
    /// <param name="this">This Number of days.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Days(this long @this) => TimeSpan.FromDays(@this);
    
    /// <summary>
    /// Creates a timespan from the given weeks.
    /// </summary>
    /// <param name="this">This Number of weeks.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Weeks(this long @this) => TimeSpan.FromDays(7*@this);
    
      
    /// <summary>
    /// Multiplies the time by a given factor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="multiplier">The multiplier.</param>
    /// <returns>A multiple of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan MultipliedWith(this TimeSpan @this, qword multiplier) => TimeSpan.FromTicks((long)(@this.Ticks * (double)multiplier));

    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan DividedBy(this TimeSpan @this, qword divisor) => TimeSpan.FromTicks((long)(@this.Ticks / (double)divisor));
    
    /// <summary>
    /// Creates a timespan from the given milliseconds.
    /// </summary>
    /// <param name="this">This Number of milliseconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Milliseconds(this qword @this) => TimeSpan.FromMilliseconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given seconds.
    /// </summary>
    /// <param name="this">This Number of seconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Seconds(this qword @this) => TimeSpan.FromSeconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given minutes.
    /// </summary>
    /// <param name="this">This Number of minutes.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Minutes(this qword @this) => TimeSpan.FromMinutes(@this);
    
    /// <summary>
    /// Creates a timespan from the given hours.
    /// </summary>
    /// <param name="this">This Number of hours.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Hours(this qword @this) => TimeSpan.FromHours(@this);
    
    /// <summary>
    /// Creates a timespan from the given days.
    /// </summary>
    /// <param name="this">This Number of days.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Days(this qword @this) => TimeSpan.FromDays(@this);
    
    /// <summary>
    /// Creates a timespan from the given weeks.
    /// </summary>
    /// <param name="this">This Number of weeks.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Weeks(this qword @this) => TimeSpan.FromDays(7*@this);
    
      
    /// <summary>
    /// Multiplies the time by a given factor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="multiplier">The multiplier.</param>
    /// <returns>A multiple of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan MultipliedWith(this TimeSpan @this, float multiplier) => TimeSpan.FromTicks((long)(@this.Ticks * multiplier));

    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan DividedBy(this TimeSpan @this, float divisor) => TimeSpan.FromTicks((long)(@this.Ticks / (double)divisor));
    
    /// <summary>
    /// Creates a timespan from the given milliseconds.
    /// </summary>
    /// <param name="this">This Number of milliseconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Milliseconds(this float @this) => TimeSpan.FromMilliseconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given seconds.
    /// </summary>
    /// <param name="this">This Number of seconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Seconds(this float @this) => TimeSpan.FromSeconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given minutes.
    /// </summary>
    /// <param name="this">This Number of minutes.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Minutes(this float @this) => TimeSpan.FromMinutes(@this);
    
    /// <summary>
    /// Creates a timespan from the given hours.
    /// </summary>
    /// <param name="this">This Number of hours.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Hours(this float @this) => TimeSpan.FromHours(@this);
    
    /// <summary>
    /// Creates a timespan from the given days.
    /// </summary>
    /// <param name="this">This Number of days.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Days(this float @this) => TimeSpan.FromDays(@this);
    
    /// <summary>
    /// Creates a timespan from the given weeks.
    /// </summary>
    /// <param name="this">This Number of weeks.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Weeks(this float @this) => TimeSpan.FromDays(7*@this);
    
      
    /// <summary>
    /// Multiplies the time by a given factor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="multiplier">The multiplier.</param>
    /// <returns>A multiple of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan MultipliedWith(this TimeSpan @this, double multiplier) => TimeSpan.FromTicks((long)(@this.Ticks * multiplier));

    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan DividedBy(this TimeSpan @this, double divisor) => TimeSpan.FromTicks((long)(@this.Ticks / (double)divisor));
    
    /// <summary>
    /// Creates a timespan from the given milliseconds.
    /// </summary>
    /// <param name="this">This Number of milliseconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Milliseconds(this double @this) => TimeSpan.FromMilliseconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given seconds.
    /// </summary>
    /// <param name="this">This Number of seconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Seconds(this double @this) => TimeSpan.FromSeconds(@this);
    
    /// <summary>
    /// Creates a timespan from the given minutes.
    /// </summary>
    /// <param name="this">This Number of minutes.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Minutes(this double @this) => TimeSpan.FromMinutes(@this);
    
    /// <summary>
    /// Creates a timespan from the given hours.
    /// </summary>
    /// <param name="this">This Number of hours.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Hours(this double @this) => TimeSpan.FromHours(@this);
    
    /// <summary>
    /// Creates a timespan from the given days.
    /// </summary>
    /// <param name="this">This Number of days.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Days(this double @this) => TimeSpan.FromDays(@this);
    
    /// <summary>
    /// Creates a timespan from the given weeks.
    /// </summary>
    /// <param name="this">This Number of weeks.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Weeks(this double @this) => TimeSpan.FromDays(7*@this);
    
      
    /// <summary>
    /// Multiplies the time by a given factor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="multiplier">The multiplier.</param>
    /// <returns>A multiple of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan MultipliedWith(this TimeSpan @this, decimal multiplier) => TimeSpan.FromTicks((long)(@this.Ticks * multiplier));

    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan DividedBy(this TimeSpan @this, decimal divisor) => TimeSpan.FromTicks((long)(@this.Ticks / (double)divisor));
    
    /// <summary>
    /// Creates a timespan from the given milliseconds.
    /// </summary>
    /// <param name="this">This Number of milliseconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Milliseconds(this decimal @this) => TimeSpan.FromMilliseconds((double)@this);
    
    /// <summary>
    /// Creates a timespan from the given seconds.
    /// </summary>
    /// <param name="this">This Number of seconds.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Seconds(this decimal @this) => TimeSpan.FromSeconds((double)@this);
    
    /// <summary>
    /// Creates a timespan from the given minutes.
    /// </summary>
    /// <param name="this">This Number of minutes.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Minutes(this decimal @this) => TimeSpan.FromMinutes((double)@this);
    
    /// <summary>
    /// Creates a timespan from the given hours.
    /// </summary>
    /// <param name="this">This Number of hours.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Hours(this decimal @this) => TimeSpan.FromHours((double)@this);
    
    /// <summary>
    /// Creates a timespan from the given days.
    /// </summary>
    /// <param name="this">This Number of days.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Days(this decimal @this) => TimeSpan.FromDays((double)@this);
    
    /// <summary>
    /// Creates a timespan from the given weeks.
    /// </summary>
    /// <param name="this">This Number of weeks.</param>
    /// <returns>A TimeSpan instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static TimeSpan Weeks(this decimal @this) => TimeSpan.FromDays(7*(double)@this);
    
  
    /// <summary>
    /// Divides the time by a divisor.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <param name="divisor">The divisor.</param>
    /// <returns>A fraction of the original timespan.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static double DividedBy(this TimeSpan @this, TimeSpan divisor) => @this.Ticks / (double)divisor.Ticks;
    
    /// <summary>
    /// Adds the given TimeSpan to the current date/time.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <returns>The resulting DateTime instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static DateTime FromNow(this TimeSpan @this) => DateTime.Now+@this;
    
    /// <summary>
    /// Adds the given TimeSpan to the current date/time.
    /// </summary>
    /// <param name="this">This TimeSpan.</param>
    /// <returns>The resulting DateTime instance.</returns>
#if NETFX_4
    [Pure]
#endif
#if NETFX_45
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
    public static DateTime FromUtcNow(this TimeSpan @this) => DateTime.UtcNow+@this;
    
  }
}