#!/usr/bin/env python3
"""
Generates the lookup tables (and golden round-trip vectors) for the retro home-computer character-set
encodings: Commodore PETSCII (C64/VIC-20, uppercase-graphics and lowercase modes), ATASCII (Atari 8-bit),
and the Amstrad CPC set.

    pip install cbmcodecs2
    python generate_retro_encodings.py

PETSCII tables come from the authoritative cbmcodecs2 package (Linus Walleij's PETSCII<->Unicode mappings;
block-graphics glyphs map to the Private Use Area U+F1xx). Outputs:
  * Corlib.Extensions/System/Text/PetsciiEncoding.Tables.g.cs  (byte->char tables, partial class)
  * Tests/Corlib.Tests/TestData/petscii_*.tsv                  (golden byte->codepoint, for round-trip tests)
"""

import os
import cbmcodecs2  # noqa: F401  (registers the codecs)

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "..", "..", "Corlib.Extensions", "System", "Text"))

# (C# field name, cbmcodecs2 codec name)
PETSCII = [
    ("_c64Uppercase", "petscii_c64en_uc"),
    ("_c64Lowercase", "petscii_c64en_lc"),
    ("_vic20Uppercase", "petscii_vic20en_uc"),
    ("_vic20Lowercase", "petscii_vic20en_lc"),
]


def decode_table(codec):
    table = []
    for b in range(256):
        try:
            ch = bytes([b]).decode(codec)
            table.append(ord(ch))
        except Exception:
            table.append(0xFFFD)  # undefined byte -> replacement char
    return table


def emit_cs(tables):
    lines = [
        "#nullable enable",
        "",
        "// <auto-generated>",
        "// Generated by Tests/Corlib.Tests/TestData/generate_retro_encodings.py from cbmcodecs2.",
        "// PETSCII byte -> Unicode code point. Block-graphics glyphs use the Private Use Area (U+F1xx).",
        "// </auto-generated>",
        "",
        "namespace System.Text;",
        "",
        "public sealed partial class PetsciiEncoding {",
    ]
    for field, codec in tables:
        t = decode_table(codec)
        lines.append(f"  internal static readonly char[] {field} = [")
        for row in range(0, 256, 16):
            cells = ", ".join(f"(char)0x{t[row + i]:04X}" for i in range(16))
            lines.append(f"    {cells},")
        lines.append("  ];")
        lines.append("")
    lines.append("}")
    path = os.path.join(SRC, "PetsciiEncoding.Tables.g.cs")
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {path}")


def emit_golden(tables):
    for field, codec in tables:
        t = decode_table(codec)
        name = field.lstrip("_")
        path = os.path.join(HERE, f"petscii_{name}.tsv")
        with open(path, "w", newline="\n") as f:
            f.write(f"# PETSCII {codec}: <byteHex>\\t<unicodeCodePointHex>. Source: cbmcodecs2.\n")
            for b in range(256):
                f.write(f"{b:02X}\t{t[b]:04X}\n")
        print(f"wrote {path}")


def main():
    emit_cs(PETSCII)
    emit_golden(PETSCII)


if __name__ == "__main__":
    main()
