#region (c)2010-2042 Hawkynt

// This file is part of Hawkynt's .NET Framework extensions.
//
// Hawkynt's .NET Framework extensions are free software:
// you can redistribute and/or modify it under the terms
// given in the LICENSE file.
//
// Hawkynt's .NET Framework extensions is distributed in the hope that
// it will be useful, but WITHOUT ANY WARRANTY without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the LICENSE file for more details.
//
// You should have received a copy of the License along with Hawkynt's
// .NET Framework extensions. If not, see
// <https://github.com/Hawkynt/C--FrameworkExtensions/blob/master/LICENSE>.

#endregion

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hawkynt.ColorProcessing.SourceGenerators;

/// <summary>
/// Produces the partial-class source files that feed each registry with compile-time
/// descriptor entries.
/// </summary>
/// <remarks>
/// <para>
/// One method per registry so the emitter stays explicit and easy to extend. All emitted
/// code uses <c>typeof(T)</c> and <c>new T()</c> — no reflection or <c>Activator</c>, so
/// trim/AOT analyzers see everything they need.
/// </para>
/// </remarks>
internal static class Emitter {

  private const string Header =
    "// <auto-generated by System.Drawing.Extensions.SourceGenerators/>\n" +
    "// Do not edit — changes will be lost on next build.\n" +
    "#nullable enable\n";

  public static void EmitScalers(SourceProductionContext ctx, ImmutableArray<RegistryCandidate> items) {
    var ordered = _Order(items);
    var sb = new StringBuilder(Header);
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine("using Hawkynt.ColorProcessing.Resizing;");
    sb.AppendLine();
    sb.AppendLine("namespace Hawkynt.ColorProcessing.Resizing;");
    sb.AppendLine();
    sb.AppendLine("partial class ScalerRegistry {");
    sb.AppendLine("  static partial void _CollectFromSourceGenerator(global::System.Collections.Generic.List<global::Hawkynt.ColorProcessing.Resizing.ScalerDescriptor> into) {");

    foreach (var c in ordered) {
      // Skip types decorated with [ScalerInfo] that do not implement one of the two scaler
      // interfaces (e.g. IDownscaler-only types). Matches the runtime-reflection filter in
      // ScalerDescriptor.FromType which returns null for them.
      if (!c.ImplementsIRescaler && !c.ImplementsIResampler)
        continue;

      var typeRef = c.FullyQualifiedTypeName;
      var args = _ResolveScalerAttributeArgs(c);
      var supportedScales = c.HasSupportedScalesStaticProperty ? $"{typeRef}.SupportedScales" : "global::System.Array.Empty<global::Hawkynt.ColorProcessing.Resizing.ScaleFactor>()";
      var isRescaler = c.ImplementsIRescaler ? "true" : "false";
      var isResampler = c.ImplementsIResampler ? "true" : "false";
      sb.Append("    into.Add(global::Hawkynt.ColorProcessing.Resizing.ScalerDescriptor.__CreateFromGenerator(");
      sb.Append("typeof(").Append(typeRef).Append("), ");
      sb.Append(args.Name).Append(", ");
      sb.Append(args.Author).Append(", ");
      sb.Append(args.Description).Append(", ");
      sb.Append(args.Url).Append(", ");
      sb.Append(args.Year).Append(", ");
      sb.Append(args.Category).Append(", ");
      sb.Append(supportedScales).Append(", ");
      sb.Append(isRescaler).Append(", ");
      sb.Append(isResampler).Append(", ");
      // Default-instance radius for resamplers — compile-time branched, zero reflection.
      if (c.ImplementsIResampler) {
        sb.Append("((global::Hawkynt.ColorProcessing.Resizing.IResampler)(object)new ").Append(typeRef).Append("()).Radius");
      } else {
        sb.Append("0");
      }
      sb.AppendLine("));");
    }

    sb.AppendLine("  }");
    sb.AppendLine("}");
    ctx.AddSource("ScalerRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
  }

  public static void EmitFilters(SourceProductionContext ctx, ImmutableArray<RegistryCandidate> items) {
    var ordered = _Order(items);
    var sb = new StringBuilder(Header);
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine("using Hawkynt.ColorProcessing.Filtering;");
    sb.AppendLine();
    sb.AppendLine("namespace Hawkynt.ColorProcessing.Filtering;");
    sb.AppendLine();
    sb.AppendLine("partial class FilterRegistry {");
    sb.AppendLine("  static partial void _CollectFromSourceGenerator(global::System.Collections.Generic.List<global::Hawkynt.ColorProcessing.Filtering.FilterDescriptor> into) {");

    foreach (var c in ordered) {
      if (!c.ImplementsIPixelFilter)
        continue;

      var typeRef = c.FullyQualifiedTypeName;
      var args = _ResolveFilterAttributeArgs(c);
      sb.Append("    into.Add(global::Hawkynt.ColorProcessing.Filtering.FilterDescriptor.__CreateFromGenerator(");
      sb.Append("typeof(").Append(typeRef).Append("), ");
      sb.Append(args.Name).Append(", ");
      sb.Append(args.Author).Append(", ");
      sb.Append(args.Description).Append(", ");
      sb.Append(args.Url).Append(", ");
      sb.Append(args.Year).Append(", ");
      sb.Append(args.Category);
      sb.AppendLine("));");
    }

    sb.AppendLine("  }");
    sb.AppendLine("}");
    ctx.AddSource("FilterRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
  }

  public static void EmitDitherers(SourceProductionContext ctx, ImmutableArray<RegistryCandidate> items) {
    var ordered = _Order(items);
    var sb = new StringBuilder(Header);
    sb.AppendLine("using System;");
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine("using Hawkynt.ColorProcessing;");
    sb.AppendLine("using Hawkynt.ColorProcessing.Dithering;");
    sb.AppendLine();
    sb.AppendLine("namespace Hawkynt.ColorProcessing.Dithering;");
    sb.AppendLine();
    sb.AppendLine("partial class DithererRegistry {");
    sb.AppendLine("  static partial void _CollectFromSourceGenerator(global::System.Collections.Generic.List<global::Hawkynt.ColorProcessing.Dithering.DithererDescriptor> into) {");

    foreach (var c in ordered) {
      if (!c.ImplementsIDitherer)
        continue;

      var typeRef = c.FullyQualifiedTypeName;
      var args = _ResolveDithererAttributeArgs(c);
      // Clean type name (strip "Ditherer" suffix).
      var simpleName = _SimpleTypeName(typeRef);
      var typeName = simpleName.EndsWith("Ditherer") ? simpleName.Substring(0, simpleName.Length - 8) : simpleName;

      if (c.HasStaticIDithererProperties) {
        foreach (var propName in c.StaticIDithererPropertyNames) {
          var name = RegistrySourceGenerator.EscapeStringLiteral($"{typeName}_{propName}");
          sb.Append("    into.Add(global::Hawkynt.ColorProcessing.Dithering.DithererDescriptor.__CreateFromGenerator(");
          sb.Append("typeof(").Append(typeRef).Append("), ");
          sb.Append(name).Append(", ");
          sb.Append(args.Author).Append(", ");
          sb.Append(args.Description).Append(", ");
          sb.Append(args.Type).Append(", ");
          sb.Append(args.Year).Append(", ");
          sb.Append("static () => (global::Hawkynt.ColorProcessing.IDitherer)").Append(typeRef).Append(".").Append(propName);
          sb.AppendLine("));");
        }
      } else if (c.HasParameterlessCtor) {
        var nameExpr = args.NameRaw is { Length: > 0 }
          ? args.Name
          : RegistrySourceGenerator.EscapeStringLiteral(simpleName.Replace("Ditherer", string.Empty));
        sb.Append("    into.Add(global::Hawkynt.ColorProcessing.Dithering.DithererDescriptor.__CreateFromGenerator(");
        sb.Append("typeof(").Append(typeRef).Append("), ");
        sb.Append(nameExpr).Append(", ");
        sb.Append(args.Author).Append(", ");
        sb.Append(args.Description).Append(", ");
        sb.Append(args.Type).Append(", ");
        sb.Append(args.Year).Append(", ");
        sb.Append("static () => (global::Hawkynt.ColorProcessing.IDitherer)(object)new ").Append(typeRef).Append("()");
        sb.AppendLine("));");
      }
    }

    sb.AppendLine("  }");
    sb.AppendLine("}");
    ctx.AddSource("DithererRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
  }

  public static void EmitQuantizers(SourceProductionContext ctx, ImmutableArray<RegistryCandidate> items) {
    var ordered = _Order(items);
    var sb = new StringBuilder(Header);
    sb.AppendLine("using System;");
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine("using Hawkynt.ColorProcessing;");
    sb.AppendLine("using Hawkynt.ColorProcessing.Quantization;");
    sb.AppendLine();
    sb.AppendLine("namespace Hawkynt.ColorProcessing.Quantization;");
    sb.AppendLine();
    sb.AppendLine("partial class QuantizerRegistry {");
    sb.AppendLine("  static partial void _CollectFromSourceGenerator(global::System.Collections.Generic.List<global::Hawkynt.ColorProcessing.Quantization.QuantizerDescriptor> into) {");

    foreach (var c in ordered) {
      if (!c.ImplementsIQuantizer)
        continue;

      var typeRef = c.FullyQualifiedTypeName;
      var args = _ResolveQuantizerAttributeArgs(c);
      var simpleName = _SimpleTypeName(typeRef);
      var typeName = simpleName.EndsWith("Quantizer") ? simpleName.Substring(0, simpleName.Length - 9) : simpleName;

      if (c.HasStaticIQuantizerProperties) {
        foreach (var propName in c.StaticIQuantizerPropertyNames) {
          var name = RegistrySourceGenerator.EscapeStringLiteral($"{typeName}_{propName}");
          sb.Append("    into.Add(global::Hawkynt.ColorProcessing.Quantization.QuantizerDescriptor.__CreateFromGenerator(");
          sb.Append("typeof(").Append(typeRef).Append("), ");
          sb.Append(name).Append(", ");
          sb.Append(args.Author).Append(", ");
          sb.Append(args.QuantizationType).Append(", ");
          sb.Append(args.Year).Append(", ");
          sb.Append(args.QualityRating).Append(", ");
          sb.Append("static () => (global::Hawkynt.ColorProcessing.IQuantizer)").Append(typeRef).Append(".").Append(propName);
          sb.AppendLine("));");
        }
      } else if (c.HasParameterlessCtor) {
        var nameExpr = args.DisplayNameRaw is { Length: > 0 }
          ? args.DisplayName
          : RegistrySourceGenerator.EscapeStringLiteral(simpleName.Replace("Quantizer", string.Empty));
        sb.Append("    into.Add(global::Hawkynt.ColorProcessing.Quantization.QuantizerDescriptor.__CreateFromGenerator(");
        sb.Append("typeof(").Append(typeRef).Append("), ");
        sb.Append(nameExpr).Append(", ");
        sb.Append(args.Author).Append(", ");
        sb.Append(args.QuantizationType).Append(", ");
        sb.Append(args.Year).Append(", ");
        sb.Append(args.QualityRating).Append(", ");
        sb.Append("static () => (global::Hawkynt.ColorProcessing.IQuantizer)(object)new ").Append(typeRef).Append("()");
        sb.AppendLine("));");
      }
    }

    sb.AppendLine("  }");
    sb.AppendLine("}");
    ctx.AddSource("QuantizerRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
  }

  private static IEnumerable<RegistryCandidate> _Order(ImmutableArray<RegistryCandidate> items)
    => items.OrderBy(i => i.FileHint, System.StringComparer.Ordinal).ThenBy(i => i.SyntaxOrder);

  private static string _SimpleTypeName(string fqn) {
    var idx = fqn.LastIndexOf('.');
    return idx < 0 ? fqn : fqn.Substring(idx + 1);
  }

  // --- Attribute argument resolution ---------------------------------------------------------

  private readonly record struct ScalerArgs(string Name, string Author, string Description, string Url, string Year, string Category);
  private readonly record struct FilterArgs(string Name, string Author, string Description, string Url, string Year, string Category);
  private readonly record struct DithererArgs(string Name, string? NameRaw, string Author, string Description, string Type, string Year);
  private readonly record struct QuantizerArgs(string DisplayName, string? DisplayNameRaw, string Author, string Year, string QualityRating, string QuantizationType);

  private static ScalerArgs _ResolveScalerAttributeArgs(RegistryCandidate c) {
    // ScalerInfoAttribute(string name) + named props: Author, Url, Year, Description, Category
    var ctor = c.Attribute.ConstructorArguments;
    var name = ctor.Count > 0 ? ctor[0].SourceLiteral : "\"\"";
    var named = _NamedLookup(c.Attribute.NamedArguments);
    return new ScalerArgs(
      Name: name,
      Author: named.TryGetValue("Author", out var a) ? a.SourceLiteral : "null",
      Description: named.TryGetValue("Description", out var d) ? d.SourceLiteral : "null",
      Url: named.TryGetValue("Url", out var u) ? u.SourceLiteral : "null",
      Year: named.TryGetValue("Year", out var y) ? y.SourceLiteral : "0",
      Category: named.TryGetValue("Category", out var cat) ? cat.SourceLiteral : "global::Hawkynt.ColorProcessing.Resizing.ScalerCategory.Rescaler"
    );
  }

  private static FilterArgs _ResolveFilterAttributeArgs(RegistryCandidate c) {
    var ctor = c.Attribute.ConstructorArguments;
    var name = ctor.Count > 0 ? ctor[0].SourceLiteral : "\"\"";
    var named = _NamedLookup(c.Attribute.NamedArguments);
    return new FilterArgs(
      Name: name,
      Author: named.TryGetValue("Author", out var a) ? a.SourceLiteral : "null",
      Description: named.TryGetValue("Description", out var d) ? d.SourceLiteral : "null",
      Url: named.TryGetValue("Url", out var u) ? u.SourceLiteral : "null",
      Year: named.TryGetValue("Year", out var y) ? y.SourceLiteral : "0",
      Category: named.TryGetValue("Category", out var cat) ? cat.SourceLiteral : "global::Hawkynt.ColorProcessing.Filtering.FilterCategory.Enhancement"
    );
  }

  private static DithererArgs _ResolveDithererAttributeArgs(RegistryCandidate c) {
    var ctor = c.Attribute.ConstructorArguments;
    var nameTv = ctor.Count > 0 ? ctor[0] : null;
    var named = _NamedLookup(c.Attribute.NamedArguments);
    return new DithererArgs(
      Name: nameTv?.SourceLiteral ?? "null",
      NameRaw: nameTv?.RawString,
      Author: named.TryGetValue("Author", out var a) ? a.SourceLiteral : "null",
      Description: named.TryGetValue("Description", out var d) ? d.SourceLiteral : "null",
      Type: named.TryGetValue("Type", out var t) ? t.SourceLiteral : "global::Hawkynt.ColorProcessing.Dithering.DitheringType.Custom",
      Year: named.TryGetValue("Year", out var y) ? y.SourceLiteral : "0"
    );
  }

  private static QuantizerArgs _ResolveQuantizerAttributeArgs(RegistryCandidate c) {
    var ctor = c.Attribute.ConstructorArguments;
    var qt = ctor.Count > 0 ? ctor[0].SourceLiteral : "global::Hawkynt.ColorProcessing.Quantization.QuantizationType.Tree";
    var named = _NamedLookup(c.Attribute.NamedArguments);
    var dispName = named.TryGetValue("DisplayName", out var dn) ? dn : null;
    return new QuantizerArgs(
      DisplayName: dispName?.SourceLiteral ?? "null",
      DisplayNameRaw: dispName?.RawString,
      Author: named.TryGetValue("Author", out var a) ? a.SourceLiteral : "null",
      Year: named.TryGetValue("Year", out var y) ? y.SourceLiteral : "0",
      QualityRating: named.TryGetValue("QualityRating", out var qr) ? qr.SourceLiteral : "0",
      QuantizationType: qt
    );
  }

  private static Dictionary<string, TypedValue> _NamedLookup(EquatableArray<NamedArg> items) {
    var d = new Dictionary<string, TypedValue>(System.StringComparer.Ordinal);
    foreach (var na in items)
      d[na.Name] = na.Value;
    return d;
  }
}
