name: NewBuild
on:
  schedule:
    - cron: '59 23 * * 0'
  workflow_dispatch:
jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
        
      - name: Show Info
        run: dotnet --info
      
      - name: Receive Version
        run: perl ".github/workflows/UpdateVersions.pl" "."

      - name: Upload entire workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace-artifacts
          path: ${{ github.workspace }}
          if-no-files-found: error

  BuildBackports:
    needs: Init
    runs-on: ubuntu-latest
    strategy:
      matrix:
        csproj-file: 
          - 'Backports/Backports.csproj'
    steps:
      - name: Download entire workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace-artifacts
          path: ${{ github.workspace }}

      - name: Restore dependencies
        run: dotnet restore "${{ matrix.csproj-file }}"
      
      - name: Build
        run: dotnet build "${{ matrix.csproj-file }}" --no-restore --configuration Release
     
      - name: Upload entire workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace-artifacts
          path: ${{ github.workspace }}
          if-no-files-found: error

  BuildExtensions:
    needs: BuildBackports
    runs-on: ubuntu-latest
    strategy:
      matrix:
        csproj-file: 
          - 'Corlib.Extensions/Corlib.Extensions.csproj'
          - 'PresentationCore.Extensions/PresentationCore.Extensions.csproj'
          - 'System.Drawing.Extensions/System.Drawing.Extensions.csproj'
          - 'System.Windows.Forms.Extensions/System.Windows.Form.Extensions.csproj'
          - 'System.DirectoryServices.AccountManagement.Extensions/DirectoryServices.Extensions.csproj'
    steps:
      - name: Download entire workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace-artifacts
          path: ${{ github.workspace }}

      - name: Restore dependencies
        run: dotnet restore "${{ matrix.csproj-file }}"
      
      - name: Build
        run: dotnet build "${{ matrix.csproj-file }}" --no-restore --configuration Release

      - name: Upload entire workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace-artifacts
          path: ${{ github.workspace }}
          if-no-files-found: error
    
#  PublishNuGet:
#    needs: BuildExtensions
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        csproj-file: ['Backports/Backports.csproj']
#    steps:
#      - name: Download entire workspace
#        uses: actions/download-artifact@v3
#        with:
#          name: workspace-artifacts
#          path: ${{ github.workspace }}
#
#      - name: Pack NuGet package
#        run: dotnet pack "${{ matrix.csproj-file }}" --configuration Release --output ./artifacts
#      
#      - name: Publish the package to nuget.org
#        run: dotnet nuget push ./artifacts/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json --skip-duplicate
#        env:
#          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
  