name:  Tests
on: 
  workflow_run:
    workflows: ["NewBuild"]
    types:
      - completed
  workflow_dispatch:
jobs:
  RunTests:
    strategy:
      fail-fast: false
      matrix:
# Ubuntu fails tests in test-runner code right now, dunno why - it's not my code
#        os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
        csproj-file: 
          - 'Tests/Corlib.Tests/Corlib.Tests.csproj'
        configuration: ['Debug','Release']
        architecture: ['AnyCPU','x86','x64']

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.x
            3.1
#            1.0
#            1.1
#            2.0
#            2.1
#            2.2
#            3.0
#            5.x
#            6.x
#            7.x

      - name: Test
        run: dotnet test "${{ matrix.csproj-file }}" --configuration ${{ matrix.configuration }} --arch ${{ matrix.architecture }} --verbosity normal /p:TreatWarningsAsErrors=false /p:NoWarn=1591;1584;1658;1573;1574;8619;8620
