name:  Tests
on: 
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  RunTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        csproj-file: ['Tests/Corlib.Tests/Corlib.Tests.csproj','Tests/Corlib.Tests/Corlib.Tests (NoUnsafe).csproj']
        configuration: ['Debug','Release']
        architecture: ['AnyCPU','x86','x64']
    
    steps:
     - uses: actions/checkout@v3
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: 7.x

     - name: Test
       run: dotnet test "${{ matrix.csproj-file }}" --configuration ${{ matrix.configuration }} --arch ${{ matrix.architecture }} --verbosity normal
     
